{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kahuna-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kahuna-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "kahuna-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.metrics.port }}
      targetPort: https
      protocol: TCP
{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kahuna-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kahuna-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kahuna-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      scheme: https
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
{{- end }}
