//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerIssuerRef) DeepCopyInto(out *CertManagerIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerIssuerRef.
func (in *CertManagerIssuerRef) DeepCopy() *CertManagerIssuerRef {
	if in == nil {
		return nil
	}
	out := new(CertManagerIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
	out.IssuerRef = in.IssuerRef
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KahunaCluster) DeepCopyInto(out *KahunaCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KahunaCluster.
func (in *KahunaCluster) DeepCopy() *KahunaCluster {
	if in == nil {
		return nil
	}
	out := new(KahunaCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KahunaCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KahunaClusterList) DeepCopyInto(out *KahunaClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KahunaCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KahunaClusterList.
func (in *KahunaClusterList) DeepCopy() *KahunaClusterList {
	if in == nil {
		return nil
	}
	out := new(KahunaClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KahunaClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KahunaClusterSpec) DeepCopyInto(out *KahunaClusterSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Partitions != nil {
		in, out := &in.Partitions, &out.Partitions
		*out = new(int32)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.TLS.DeepCopyInto(&out.TLS)
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new(PortsSpec)
		**out = **in
	}
	if in.Raft != nil {
		in, out := &in.Raft, &out.Raft
		*out = new(RaftSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Transactions != nil {
		in, out := &in.Transactions, &out.Transactions
		*out = new(TransactionsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(WorkersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KahunaClusterSpec.
func (in *KahunaClusterSpec) DeepCopy() *KahunaClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KahunaClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KahunaClusterStatus) DeepCopyInto(out *KahunaClusterStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MemberStatus, len(*in))
		copy(*out, *in)
	}
	if in.UpdatePartition != nil {
		in, out := &in.UpdatePartition, &out.UpdatePartition
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KahunaClusterStatus.
func (in *KahunaClusterStatus) DeepCopy() *KahunaClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KahunaClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberStatus) DeepCopyInto(out *MemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberStatus.
func (in *MemberStatus) DeepCopy() *MemberStatus {
	if in == nil {
		return nil
	}
	out := new(MemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortsSpec) DeepCopyInto(out *PortsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortsSpec.
func (in *PortsSpec) DeepCopy() *PortsSpec {
	if in == nil {
		return nil
	}
	out := new(PortsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RaftSpec) DeepCopyInto(out *RaftSpec) {
	*out = *in
	if in.HeartbeatIntervalMs != nil {
		in, out := &in.HeartbeatIntervalMs, &out.HeartbeatIntervalMs
		*out = new(int32)
		**out = **in
	}
	if in.VotingTimeoutMs != nil {
		in, out := &in.VotingTimeoutMs, &out.VotingTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.StartElectionTimeoutMs != nil {
		in, out := &in.StartElectionTimeoutMs, &out.StartElectionTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.EndElectionTimeoutMs != nil {
		in, out := &in.EndElectionTimeoutMs, &out.EndElectionTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.EnableCheckQuorum != nil {
		in, out := &in.EnableCheckQuorum, &out.EnableCheckQuorum
		*out = new(bool)
		**out = **in
	}
	if in.GossipIntervalMs != nil {
		in, out := &in.GossipIntervalMs, &out.GossipIntervalMs
		*out = new(int32)
		**out = **in
	}
	if in.GossipFanout != nil {
		in, out := &in.GossipFanout, &out.GossipFanout
		*out = new(int32)
		**out = **in
	}
	if in.PingTimeoutMs != nil {
		in, out := &in.PingTimeoutMs, &out.PingTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.IndirectPingFanout != nil {
		in, out := &in.IndirectPingFanout, &out.IndirectPingFanout
		*out = new(int32)
		**out = **in
	}
	if in.SuspicionTimeoutMs != nil {
		in, out := &in.SuspicionTimeoutMs, &out.SuspicionTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.DeadMemberEvictionGraceMs != nil {
		in, out := &in.DeadMemberEvictionGraceMs, &out.DeadMemberEvictionGraceMs
		*out = new(int32)
		**out = **in
	}
	if in.BackfillThreshold != nil {
		in, out := &in.BackfillThreshold, &out.BackfillThreshold
		*out = new(int32)
		**out = **in
	}
	if in.MaxBackfillEntriesPerRound != nil {
		in, out := &in.MaxBackfillEntriesPerRound, &out.MaxBackfillEntriesPerRound
		*out = new(int32)
		**out = **in
	}
	if in.LearnerPromotionLag != nil {
		in, out := &in.LearnerPromotionLag, &out.LearnerPromotionLag
		*out = new(int32)
		**out = **in
	}
	if in.LearnerPromotionStableWindowMs != nil {
		in, out := &in.LearnerPromotionStableWindowMs, &out.LearnerPromotionStableWindowMs
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RaftSpec.
func (in *RaftSpec) DeepCopy() *RaftSpec {
	if in == nil {
		return nil
	}
	out := new(RaftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.Data.DeepCopyInto(&out.Data)
	if in.WAL != nil {
		in, out := &in.WAL, &out.WAL
		*out = new(VolumeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SyncWrites != nil {
		in, out := &in.SyncWrites, &out.SyncWrites
		*out = new(bool)
		**out = **in
	}
	if in.DirectReads != nil {
		in, out := &in.DirectReads, &out.DirectReads
		*out = new(bool)
		**out = **in
	}
	if in.SharedMemory != nil {
		in, out := &in.SharedMemory, &out.SharedMemory
		*out = new(bool)
		**out = **in
	}
	if in.SharedMemoryBudgetMB != nil {
		in, out := &in.SharedMemoryBudgetMB, &out.SharedMemoryBudgetMB
		*out = new(int32)
		**out = **in
	}
	if in.SharedMemtableBudgetMB != nil {
		in, out := &in.SharedMemtableBudgetMB, &out.SharedMemtableBudgetMB
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransactionsSpec) DeepCopyInto(out *TransactionsSpec) {
	*out = *in
	if in.DefaultTimeoutMs != nil {
		in, out := &in.DefaultTimeoutMs, &out.DefaultTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.DefaultAdmissionWaitMs != nil {
		in, out := &in.DefaultAdmissionWaitMs, &out.DefaultAdmissionWaitMs
		*out = new(int32)
		**out = **in
	}
	if in.MaxAdmissionWaitMs != nil {
		in, out := &in.MaxAdmissionWaitMs, &out.MaxAdmissionWaitMs
		*out = new(int32)
		**out = **in
	}
	if in.MaxConcurrentTransactions != nil {
		in, out := &in.MaxConcurrentTransactions, &out.MaxConcurrentTransactions
		*out = new(int32)
		**out = **in
	}
	if in.MaxConcurrentSessions != nil {
		in, out := &in.MaxConcurrentSessions, &out.MaxConcurrentSessions
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransactionsSpec.
func (in *TransactionsSpec) DeepCopy() *TransactionsSpec {
	if in == nil {
		return nil
	}
	out := new(TransactionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkersSpec) DeepCopyInto(out *WorkersSpec) {
	*out = *in
	if in.Locks != nil {
		in, out := &in.Locks, &out.Locks
		*out = new(int32)
		**out = **in
	}
	if in.KeyValue != nil {
		in, out := &in.KeyValue, &out.KeyValue
		*out = new(int32)
		**out = **in
	}
	if in.Sequencer != nil {
		in, out := &in.Sequencer, &out.Sequencer
		*out = new(int32)
		**out = **in
	}
	if in.BackgroundWriter != nil {
		in, out := &in.BackgroundWriter, &out.BackgroundWriter
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkersSpec.
func (in *WorkersSpec) DeepCopy() *WorkersSpec {
	if in == nil {
		return nil
	}
	out := new(WorkersSpec)
	in.DeepCopyInto(out)
	return out
}
